# Generated by Django 5.0.7 on 2024-07-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
