# Generated by Django 5.0.7 on 2024-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_booking_guests_booking_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.BigIntegerField(),
        ),
    ]
