# Generated by Django 5.0.7 on 2024-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
