# Generated by Django 5.0.7 on 2024-09-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_comment_parent_alter_comment_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rooms',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_modified',
        ),
    ]
