# Generated by Django 5.0.7 on 2024-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_zarinpal_authority_order_zarinpal_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_night',
            field=models.IntegerField(),
        ),
    ]
